// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: fastrtb/bid_response.proto

package fastrtb

import (
	formats "github.com/c-wire/fastrtb/formats"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"` // corresponding request ID from the BidRequest. This can be useful if streams are used
	// actaul hiararchy of the bids (if we sort them by impression or buyer or something else) is TBD
	Bids []*Bid `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fastrtb_bid_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fastrtb_bid_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_fastrtb_bid_response_proto_rawDescGZIP(), []int{0}
}

func (x *BidResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BidResponse) GetBids() []*Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

type Bid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                     // ID of the bid. should be UUIDv7
	ImpressionId string  `protobuf:"bytes,2,opt,name=impressionId,proto3" json:"impressionId,omitempty"` // ID of the impression we are bidding on (there can be multiple bids for the same impression)
	BidPrice     float64 `protobuf:"fixed64,3,opt,name=bidPrice,proto3" json:"bidPrice,omitempty"`       // cpm bid Price
	// Types that are assignable to Ad:
	//	*Bid_BannerAd
	//	*Bid_SearchContextAd
	Ad         isBid_Ad    `protobuf_oneof:"ad"`
	Buyer      string      `protobuf:"bytes,6,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Reporting  *Reporting  `protobuf:"bytes,7,opt,name=reporting,proto3" json:"reporting,omitempty"` // this should be refactored into a standardized reporting endpoint to allow 3rd party reporting services
	AdMetaData *AdMetaData `protobuf:"bytes,8,opt,name=adMetaData,proto3" json:"adMetaData,omitempty"`
}

func (x *Bid) Reset() {
	*x = Bid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fastrtb_bid_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_fastrtb_bid_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_fastrtb_bid_response_proto_rawDescGZIP(), []int{1}
}

func (x *Bid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bid) GetImpressionId() string {
	if x != nil {
		return x.ImpressionId
	}
	return ""
}

func (x *Bid) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (m *Bid) GetAd() isBid_Ad {
	if m != nil {
		return m.Ad
	}
	return nil
}

func (x *Bid) GetBannerAd() *formats.BannerAd {
	if x, ok := x.GetAd().(*Bid_BannerAd); ok {
		return x.BannerAd
	}
	return nil
}

func (x *Bid) GetSearchContextAd() *formats.SearchContextAd {
	if x, ok := x.GetAd().(*Bid_SearchContextAd); ok {
		return x.SearchContextAd
	}
	return nil
}

func (x *Bid) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *Bid) GetReporting() *Reporting {
	if x != nil {
		return x.Reporting
	}
	return nil
}

func (x *Bid) GetAdMetaData() *AdMetaData {
	if x != nil {
		return x.AdMetaData
	}
	return nil
}

type isBid_Ad interface {
	isBid_Ad()
}

type Bid_BannerAd struct {
	BannerAd *formats.BannerAd `protobuf:"bytes,4,opt,name=bannerAd,proto3,oneof"`
}

type Bid_SearchContextAd struct {
	SearchContextAd *formats.SearchContextAd `protobuf:"bytes,5,opt,name=searchContextAd,proto3,oneof"`
}

func (*Bid_BannerAd) isBid_Ad() {}

func (*Bid_SearchContextAd) isBid_Ad() {}

// used for ad quality schemes
type AdMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreativeId string `protobuf:"bytes,1,opt,name=creativeId,proto3" json:"creativeId,omitempty"`
	CampaignId string `protobuf:"bytes,2,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
}

func (x *AdMetaData) Reset() {
	*x = AdMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fastrtb_bid_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdMetaData) ProtoMessage() {}

func (x *AdMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_fastrtb_bid_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdMetaData.ProtoReflect.Descriptor instead.
func (*AdMetaData) Descriptor() ([]byte, []int) {
	return file_fastrtb_bid_response_proto_rawDescGZIP(), []int{2}
}

func (x *AdMetaData) GetCreativeId() string {
	if x != nil {
		return x.CreativeId
	}
	return ""
}

func (x *AdMetaData) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type Reporting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinNoticeUrl     string `protobuf:"bytes,1,opt,name=winNoticeUrl,proto3" json:"winNoticeUrl,omitempty"`
	BillingNoticeUrl string `protobuf:"bytes,2,opt,name=billingNoticeUrl,proto3" json:"billingNoticeUrl,omitempty"`
	LossNoticeUrl    string `protobuf:"bytes,3,opt,name=lossNoticeUrl,proto3" json:"lossNoticeUrl,omitempty"`
}

func (x *Reporting) Reset() {
	*x = Reporting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fastrtb_bid_response_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reporting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reporting) ProtoMessage() {}

func (x *Reporting) ProtoReflect() protoreflect.Message {
	mi := &file_fastrtb_bid_response_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reporting.ProtoReflect.Descriptor instead.
func (*Reporting) Descriptor() ([]byte, []int) {
	return file_fastrtb_bid_response_proto_rawDescGZIP(), []int{3}
}

func (x *Reporting) GetWinNoticeUrl() string {
	if x != nil {
		return x.WinNoticeUrl
	}
	return ""
}

func (x *Reporting) GetBillingNoticeUrl() string {
	if x != nil {
		return x.BillingNoticeUrl
	}
	return ""
}

func (x *Reporting) GetLossNoticeUrl() string {
	if x != nil {
		return x.LossNoticeUrl
	}
	return ""
}

var File_fastrtb_bid_response_proto protoreflect.FileDescriptor

var file_fastrtb_bid_response_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x66, 0x61, 0x73, 0x74, 0x72, 0x74, 0x62, 0x2f, 0x62, 0x69, 0x64, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x61,
	0x73, 0x74, 0x72, 0x74, 0x62, 0x1a, 0x27, 0x66, 0x61, 0x73, 0x74, 0x72, 0x74, 0x62, 0x2f, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x66, 0x61, 0x73, 0x74, 0x72, 0x74, 0x62, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2f,
	0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4d, 0x0a, 0x0b, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x04,
	0x62, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x66, 0x61, 0x73,
	0x74, 0x72, 0x74, 0x62, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x22, 0xdf,
	0x02, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6d, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6d,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x69,
	0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x62, 0x69,
	0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x41, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x61, 0x73, 0x74, 0x72,
	0x74, 0x62, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x72, 0x41, 0x64, 0x48, 0x00, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x12,
	0x4c, 0x0a, 0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x41, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x61, 0x73, 0x74, 0x72,
	0x74, 0x62, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x41, 0x64, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x41, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x75, 0x79, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x75,
	0x79, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x61, 0x73, 0x74, 0x72, 0x74, 0x62,
	0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x33, 0x0a, 0x0a, 0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x61, 0x73, 0x74,
	0x72, 0x74, 0x62, 0x2e, 0x41, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0a,
	0x61, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x42, 0x04, 0x0a, 0x02, 0x61, 0x64,
	0x22, 0x4c, 0x0a, 0x0a, 0x41, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x76, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x76, 0x65, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x22, 0x81,
	0x01, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0c,
	0x77, 0x69, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x77, 0x69, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x55, 0x72, 0x6c,
	0x12, 0x2a, 0x0a, 0x10, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x74, 0x69, 0x63,
	0x65, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x62, 0x69, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x24, 0x0a, 0x0d,
	0x6c, 0x6f, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x6f, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x55,
	0x72, 0x6c, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x2d, 0x77, 0x69, 0x72, 0x65, 0x2f, 0x66, 0x61, 0x73, 0x74, 0x72, 0x74, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fastrtb_bid_response_proto_rawDescOnce sync.Once
	file_fastrtb_bid_response_proto_rawDescData = file_fastrtb_bid_response_proto_rawDesc
)

func file_fastrtb_bid_response_proto_rawDescGZIP() []byte {
	file_fastrtb_bid_response_proto_rawDescOnce.Do(func() {
		file_fastrtb_bid_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_fastrtb_bid_response_proto_rawDescData)
	})
	return file_fastrtb_bid_response_proto_rawDescData
}

var file_fastrtb_bid_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fastrtb_bid_response_proto_goTypes = []interface{}{
	(*BidResponse)(nil),             // 0: fastrtb.BidResponse
	(*Bid)(nil),                     // 1: fastrtb.Bid
	(*AdMetaData)(nil),              // 2: fastrtb.AdMetaData
	(*Reporting)(nil),               // 3: fastrtb.Reporting
	(*formats.BannerAd)(nil),        // 4: fastrtb.formats.BannerAd
	(*formats.SearchContextAd)(nil), // 5: fastrtb.formats.SearchContextAd
}
var file_fastrtb_bid_response_proto_depIdxs = []int32{
	1, // 0: fastrtb.BidResponse.bids:type_name -> fastrtb.Bid
	4, // 1: fastrtb.Bid.bannerAd:type_name -> fastrtb.formats.BannerAd
	5, // 2: fastrtb.Bid.searchContextAd:type_name -> fastrtb.formats.SearchContextAd
	3, // 3: fastrtb.Bid.reporting:type_name -> fastrtb.Reporting
	2, // 4: fastrtb.Bid.adMetaData:type_name -> fastrtb.AdMetaData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fastrtb_bid_response_proto_init() }
func file_fastrtb_bid_response_proto_init() {
	if File_fastrtb_bid_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fastrtb_bid_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fastrtb_bid_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fastrtb_bid_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fastrtb_bid_response_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reporting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_fastrtb_bid_response_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Bid_BannerAd)(nil),
		(*Bid_SearchContextAd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fastrtb_bid_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fastrtb_bid_response_proto_goTypes,
		DependencyIndexes: file_fastrtb_bid_response_proto_depIdxs,
		MessageInfos:      file_fastrtb_bid_response_proto_msgTypes,
	}.Build()
	File_fastrtb_bid_response_proto = out.File
	file_fastrtb_bid_response_proto_rawDesc = nil
	file_fastrtb_bid_response_proto_goTypes = nil
	file_fastrtb_bid_response_proto_depIdxs = nil
}
