// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: fastrtb/formats/banner_ad_request.proto

package formats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BannerAdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sizes []*Size `protobuf:"bytes,1,rep,name=sizes,proto3" json:"sizes,omitempty"`
}

func (x *BannerAdRequest) Reset() {
	*x = BannerAdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fastrtb_formats_banner_ad_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BannerAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerAdRequest) ProtoMessage() {}

func (x *BannerAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fastrtb_formats_banner_ad_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerAdRequest.ProtoReflect.Descriptor instead.
func (*BannerAdRequest) Descriptor() ([]byte, []int) {
	return file_fastrtb_formats_banner_ad_request_proto_rawDescGZIP(), []int{0}
}

func (x *BannerAdRequest) GetSizes() []*Size {
	if x != nil {
		return x.Sizes
	}
	return nil
}

var File_fastrtb_formats_banner_ad_request_proto protoreflect.FileDescriptor

var file_fastrtb_formats_banner_ad_request_proto_rawDesc = []byte{
	0x0a, 0x27, 0x66, 0x61, 0x73, 0x74, 0x72, 0x74, 0x62, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x73, 0x2f, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x66, 0x61, 0x73, 0x74, 0x72,
	0x74, 0x62, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x1a, 0x1a, 0x66, 0x61, 0x73, 0x74,
	0x72, 0x74, 0x62, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2f, 0x6d, 0x69, 0x73, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x0f, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x41, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x69, 0x7a,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x61, 0x73, 0x74, 0x72,
	0x74, 0x62, 0x2e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x52,
	0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x2d, 0x77, 0x69, 0x72, 0x65, 0x2f, 0x66, 0x61, 0x73, 0x74,
	0x72, 0x74, 0x62, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_fastrtb_formats_banner_ad_request_proto_rawDescOnce sync.Once
	file_fastrtb_formats_banner_ad_request_proto_rawDescData = file_fastrtb_formats_banner_ad_request_proto_rawDesc
)

func file_fastrtb_formats_banner_ad_request_proto_rawDescGZIP() []byte {
	file_fastrtb_formats_banner_ad_request_proto_rawDescOnce.Do(func() {
		file_fastrtb_formats_banner_ad_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_fastrtb_formats_banner_ad_request_proto_rawDescData)
	})
	return file_fastrtb_formats_banner_ad_request_proto_rawDescData
}

var file_fastrtb_formats_banner_ad_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fastrtb_formats_banner_ad_request_proto_goTypes = []interface{}{
	(*BannerAdRequest)(nil), // 0: fastrtb.formats.BannerAdRequest
	(*Size)(nil),            // 1: fastrtb.formats.Size
}
var file_fastrtb_formats_banner_ad_request_proto_depIdxs = []int32{
	1, // 0: fastrtb.formats.BannerAdRequest.sizes:type_name -> fastrtb.formats.Size
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_fastrtb_formats_banner_ad_request_proto_init() }
func file_fastrtb_formats_banner_ad_request_proto_init() {
	if File_fastrtb_formats_banner_ad_request_proto != nil {
		return
	}
	file_fastrtb_formats_misc_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_fastrtb_formats_banner_ad_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BannerAdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fastrtb_formats_banner_ad_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fastrtb_formats_banner_ad_request_proto_goTypes,
		DependencyIndexes: file_fastrtb_formats_banner_ad_request_proto_depIdxs,
		MessageInfos:      file_fastrtb_formats_banner_ad_request_proto_msgTypes,
	}.Build()
	File_fastrtb_formats_banner_ad_request_proto = out.File
	file_fastrtb_formats_banner_ad_request_proto_rawDesc = nil
	file_fastrtb_formats_banner_ad_request_proto_goTypes = nil
	file_fastrtb_formats_banner_ad_request_proto_depIdxs = nil
}
